CC=gcc
ProgName=jacobian_alg
SrcFile=jacobian.c
CompCli= #Nothing to use right now
CliRun= 3 0.001

all: compile run 

compile: 
	$(CC) -o $(ProgName) $(CompCli) $(SrcFile)

run: 
	./$(ProgName) $(CliRun)